// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PTMS.Infrastructure.Postgre.Data;

namespace PTMS.Infrastructure.Postgre.Data.Migrations
{
    [DbContext(typeof(PtmsDataStore))]
    [Migration("20210121145136_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ptms")
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("PTMS.Infrastructure.Postgre.Data.DbEntities.DbCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PTMS.Infrastructure.Postgre.Data.DbEntities.DbMargin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bottom")
                        .HasColumnType("text");

                    b.Property<string>("Left")
                        .HasColumnType("text");

                    b.Property<string>("Right")
                        .HasColumnType("text");

                    b.Property<string>("Top")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Margins");
                });

            modelBuilder.Entity("PTMS.Infrastructure.Postgre.Data.DbEntities.DbOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DisplayHeaderFooter")
                        .HasColumnType("boolean");

                    b.Property<string>("FooterTemplate")
                        .HasColumnType("text");

                    b.Property<string>("Format")
                        .HasColumnType("text");

                    b.Property<string>("HeaderTemplate")
                        .HasColumnType("text");

                    b.Property<bool>("Landscape")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MarginId")
                        .HasColumnType("uuid");

                    b.Property<bool>("PrintBackground")
                        .HasColumnType("boolean");

                    b.Property<int>("Scale")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MarginId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("PTMS.Infrastructure.Postgre.Data.DbEntities.DbPartial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Editor")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("TemplateBody")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Version")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.ToTable("Partials");
                });

            modelBuilder.Entity("PTMS.Infrastructure.Postgre.Data.DbEntities.DbTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Caching")
                        .HasColumnType("boolean");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<long>("Created")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Editor")
                        .HasColumnType("text");

                    b.Property<bool>("LoadExternalSources")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TemplateBody")
                        .HasColumnType("text");

                    b.Property<long>("Updated")
                        .HasColumnType("bigint");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OptionId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("PTMS.Infrastructure.Postgre.Data.DbEntities.DbVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Creator")
                        .HasColumnType("text");

                    b.Property<string>("TemplateBody")
                        .HasColumnType("text");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("VersionNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("DbVersion");
                });

            modelBuilder.Entity("PTMS.Infrastructure.Postgre.Data.DbEntities.DbOption", b =>
                {
                    b.HasOne("PTMS.Infrastructure.Postgre.Data.DbEntities.DbMargin", "Margin")
                        .WithMany()
                        .HasForeignKey("MarginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Margin");
                });

            modelBuilder.Entity("PTMS.Infrastructure.Postgre.Data.DbEntities.DbTemplate", b =>
                {
                    b.HasOne("PTMS.Infrastructure.Postgre.Data.DbEntities.DbOption", "Options")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Options");
                });

            modelBuilder.Entity("PTMS.Infrastructure.Postgre.Data.DbEntities.DbVersion", b =>
                {
                    b.HasOne("PTMS.Infrastructure.Postgre.Data.DbEntities.DbTemplate", "Template")
                        .WithMany("Versions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("PTMS.Infrastructure.Postgre.Data.DbEntities.DbTemplate", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
